services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk-dev
    hostname: splunk-dev
    ports:
      - "0.0.0.0:8000:8000"
      - "0.0.0.0:8443:8443"   
      - "0.0.0.0:8088:8088"
      - "0.0.0.0:8089:8089"
    volumes:
      - ./volumes/splunk-etc:/opt/splunk/etc
      - ./volumes/splunk-var:/opt/splunk/var
      - ./volumes/app-logs:/var/log/applications:ro
      - ./security:/opt/splunk/etc/auth/mycerts   
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=ChangeMePlease123!
      - SPLUNK_HEC_TOKEN=abcd1234-ef56-7890-gh12-ijklmnop3456
    restart: unless-stopped

  log-generator:
    image: python:3.9-slim
    container_name: log-generator
    volumes:
      - ./volumes/app-logs:/var/log/applications
      - ./containers/log-generator:/app
    working_dir: /app
    command: python generate_logs.py
    restart: unless-stopped
    depends_on:
      - splunk

networks:
  default:
    driver: bridge