trigger:
- main

pool: 
  name: 'splunk-dev-pool'

parameters:
- name: target_component
  displayName: 'Deploy to Component'
  type: string
  default: 'splunk_dev'
  values:
  - splunk_dev
  - deployment_server
  - all_components

- name: restart_services
  displayName: 'Restart Splunk after deployment'
  type: boolean
  default: true

variables:
# MODIFICATION: Link to the variable group containing the secret password
- group: Agent-Credentials
# MODIFICATION: Update the path to the new directory location
  DOCK-ER_COMPOSE_PATH: '/opt/splunk-docker-dev'
  DEPLOYMENT_PATH: '/opt/deployments/splunk'

stages:
- stage: Deploy
  displayName: 'Deploy Configuration'
  jobs:
  - job: DeployJob
    displayName: 'Deploy to ${{ parameters.target_component }}'
    steps:
    - checkout: self

    - script: |
        echo "Deploying to: ${{ parameters.target_component }}"
        echo "Restart services: ${{ parameters.restart_services }}"
      displayName: 'Deployment Info'

    - ${{ if eq(parameters.target_component, 'splunk_dev') }}:
      - script: |
          echo "Deploying apps to Splunk dev container..."
          
          # MODIFICATION: Pipe the password to sudo for each command
          echo "$(AGENT_SUDO_PASSWORD)" | sudo -S cp -r apps/* $(DOCKER_COMPOSE_PATH)/volumes/splunk-etc/apps/
          echo "$(AGENT_SUDO_PASSWORD)" | sudo -S cp indexer-cluster/master-node/indexes.conf $(DOCKER_COMPOSE_PATH)/volumes/splunk-etc/system/local/
          echo "$(AGENT_SUDO_PASSWORD)" | sudo -S chown -R 41812:41812 $(DOCKER_COMPOSE_PATH)/volumes/splunk-etc/
          
          echo "Deployed to Splunk dev container successfully"
        displayName: 'Deploy to Splunk Dev'
        # MODIFICATION: Map the secret to an environment variable for this script
        env:
          AGENT_SUDO_PASSWORD: $(AGENT_SUDO_PASSWORD)

    - ${{ if eq(parameters.target_component, 'all_components') }}:
      - script: |
          echo "Deploying to all targets..."
          
          # MODIFICATION: Pipe the password to sudo for each command
          echo "$(AGENT_SUDO_PASSWORD)" | sudo -S cp -r apps/* $(DOCKER_COMPOSE_PATH)/volumes/splunk-etc/apps/
          echo "$(AGENT_SUDO_PASSWORD)" | sudo -S cp indexer-cluster/master-node/indexes.conf $(DOCKER_COMPOSE_PATH)/volumes/splunk-etc/system/local/
          echo "$(AGENT_SUDO_PASSWORD)" | sudo -S chown -R 41812:41812 $(DOCKER_COMPOSE_PATH)/volumes/splunk-etc/
          
          echo "$(AGENT_SUDO_PASSWORD)" | sudo -S mkdir -p $(DEPLOYMENT_PATH)
          echo "$(AGENT_SUDO_PASSWORD)" | sudo -S cp -r deployment-server/* $(DEPLOYMENT_PATH)/
          echo "$(AGENT_SUDO_PASSWORD)" | sudo -S chown -R azureagent:azureagent $(DEPLOYMENT_PATH)
          
          echo "Deployed to all components successfully"
        displayName: 'Deploy to All Components'
        # MODIFICATION: Map the secret to an environment variable for this script
        env:
          AGENT_SUDO_PASSWORD: $(AGENT_SUDO_PASSWORD)

    - ${{ if eq(parameters.restart_services, true) }}:
      - script: |
          echo "Restarting Splunk services..."
          cd $(DOCKER_COMPOSE_PATH)
          
          docker-compose restart splunk
          
          echo "Waiting for Splunk to start..."
          sleep 60
          
          echo "Splunk services restarted successfully"
        displayName: 'Restart Splunk Services'

    - script: |
        echo "Validating deployment..."
        cd $(DOCKER_COMPOSE_PATH)
        
        # Check if container is running
        if docker ps | grep -q splunk-dev; then
          echo "✓ Splunk container is running"
        else
          echo "✗ Splunk container is not running"
          exit 1
        fi
        
        # Wait a bit more and check web interface
        sleep 30
        if curl -s http://localhost:8000 > /dev/null; then
          echo "✓ Splunk web interface is accessible"
        else
          echo "✗ Splunk web interface is not responding"
          exit 1
        fi
        
        # Check deployed files
        echo "Checking deployed apps:"
        docker exec splunk-dev ls -la /opt/splunk/etc/apps/ | grep custom_logging && echo "✓ custom_logging app deployed" || echo "✗ custom_logging not found"
        
        echo "Checking deployed indexes:"
        docker exec splunk-dev ls -la /opt/splunk/etc/system/local/ | grep indexes.conf && echo "✓ indexes.conf deployed" || echo "✗ indexes.conf not found"
        
        echo "Deployment validation completed"
      displayName: 'Validate Deployment'