trigger:
- main

pool: 
  name: 'splunk-dev-pool'

parameters:
- name: target_component
  displayName: 'Deploy to Component'
  type: string
  default: 'splunk_dev'
  values:
  - splunk_dev
  - deployment_server
  - all_components

- name: restart_services
  displayName: 'Restart Splunk after deployment'
  type: boolean
  default: true

stages:
- stage: Deploy
  displayName: 'Deploy and Manage Splunk Stack'
  variables:
  - group: Agent-Credentials
  - group: SPLUNK_VARIABLES
  - name: DOCKER_PROJECT_PATH
    value: '/opt/splunk-docker-dev'

  jobs:
  - job: DeployJob
    displayName: 'Deploying to ${{ parameters.target_component }}'
    steps:
    - checkout: self
      persistCredentials: true

    - script: |
        echo "Shutting down existing Splunk stack..."
        cd $(DOCKER_PROJECT_PATH)
        docker compose down --remove-orphans || echo "No existing stack found. Continuing..."
      displayName: '1. Shutdown Existing Docker Stack'

    - script: |
        echo "Syncing repository to project directory..."
        cp -R ./* $(DOCKER_PROJECT_PATH)/
      displayName: '2. Sync Repository to Project Directory'

    - script: |
        echo "Launching new Splunk stack..."
        cd $(DOCKER_PROJECT_PATH)
        docker compose up -d
      displayName: '3. Launch New Docker Stack'

    - ${{ if eq(parameters.target_component, 'splunk_dev') }}:
      - script: |
          echo "Deploying Splunk configurations..."
          echo "$(AGENT_SUDO_PASSWORD)" | sudo -S cp -r apps/* $(DOCKER_PROJECT_PATH)/volumes/splunk-etc/apps/
          echo "$(AGENT_SUDO_PASSWORD)" | sudo -S cp indexer-cluster/master-node/indexes.conf $(DOCKER_PROJECT_PATH)/volumes/splunk-etc/system/local/
          echo "$(AGENT_SUDO_PASSWORD)" | sudo -S chown -R 41812:41812 $(DOCKER_PROJECT_PATH)/volumes/splunk-etc/
        displayName: '4. Deploy Splunk Configurations'
        env:
          AGENT_SUDO_PASSWORD: $(AGENT_SUDO_PASSWORD)

    - script: |
        echo "Performing health check on Splunk container..."
        timeout=300
        interval=10
        elapsed=0
        
        while [ $elapsed -lt $timeout ]; do
          status=$(docker ps --filter "name=splunk-dev" --format "{{.Status}}")
          if [[ $status == *" (healthy)"* ]]; then
            echo "Splunk container is healthy."
            echo "Validating deployment..."
            docker exec splunk-dev ls -la /opt/splunk/etc/apps/ | grep custom_logging && echo "custom_logging app deployed" || (echo "custom_logging not found" && exit 1)
            docker exec splunk-dev ls -la /opt/splunk/etc/system/local/ | grep indexes.conf && echo "indexes.conf deployed" || (echo "indexes.conf not found" && exit 1)
            echo "Deployment validation completed successfully."
            exit 0
          fi
          echo "Waiting for Splunk to become healthy... (Status: $status)"
          sleep $interval
          elapsed=$((elapsed + interval))
        done
        
        echo "Timeout reached. Splunk container did not become healthy."
        docker logs splunk-dev
        exit 1
      displayName: '5. Health Check and Validate Deployment'

    - script: |
        echo "Mirroring repository to GitHub..."
        
        
        git config --global user.email "azure-pipeline@splunk-dev.local"
        git config --global user.name "Azure DevOps Pipeline"
        
        
        git remote add github https://$(GITHUB_PAT_TOKEN)@github.com/b00ls0ck3t/Splunk-Development.git 2>/dev/null || true
        
        
        git push github HEAD:main --force
        
        echo "Successfully mirrored to GitHub"
      displayName: '6. Mirror to GitHub'
      env:
        GITHUB_PAT_TOKEN: $(GITHUB_PAT_TOKEN)